### Start the HelloWorld orchestration function.
POST http://localhost:7071/api/start/HelloWorldOrchestration


### Check the status of the Hello World function.
### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@orchestrationInstanceId = 251372305f484f1e9a54799d4804c505
@storageCode = GLoOdgAOebifkr6wfEqmaMSAzrwtRlrSRw7O/gtiarfvo2ofQGmqXQ==
@hubName=DurableDemo
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub={{hubName}}
    &connection=Storage
    &code={{storageCode}}


### Start the HelloWorld orchestration function and wait until its completion.
POST http://localhost:7071/api/startandwait/HelloWorldOrchestration
    ?timeout=12
    &interval=3