### Start the HelloWorldOrchestrator function.
POST http://localhost:7071/api/start/HelloWorldOrchestrator


### Check the status of the HelloWorldOrchestrator function.
### Update this orchestratorInstanceId so it matches the ID of your
### running orchestrator instance.
@orchestratorInstanceId = 251372305f484f1e9a54799d4804c505
@storageCode = 1BydX/YVRj1/olUY7XxQ7Lf1xFs9seG00DUa3hl1grb2ehoS5T3bCQ==
@hubName=DurableDemo
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestratorInstanceId}}
    ?taskHub={{hubName}}
    &connection=Storage
    &code={{storageCode}}


### Start the HelloWorldOrchestrator function and wait until its completion.
POST http://localhost:7071/api/startandwait/HelloWorldOrchestrator
    ?timeout=12
    &interval=3