@outputFormat = json
@mode = driving
@key = 
@origin = 52.1500303,4.6827815
@destination = haarlem
@arrivaltimeseconds = 
https://maps.googleapis.com/maps/api/directions/{{outputFormat}}
    ?origin={{origin}}
    &destination={{destination}}
    &mode={{mode}}
    &arrival_time={{arrivaltimeseconds}}
    &key={{key}}