### Asynchronous call the Hello Name Orchestration Function
POST http://localhost:7071/api/orchestration/HelloName
Content-Type: application/json

"Serverless Computing London"


### Synchronous call the Hello Name Orchestration Function
POST http://localhost:7071/api/orchestration/HelloName/wait
    ?timeout=9
    &interval=3
Content-Type: application/json

"Serverless Computing London"

### Check the status of the Hello World function.
### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@orchestrationInstanceId = 98ce0997452c4671ab99cd8c593f535b
@storageCode = jLm5dvj2FG6pIVhnZaI2Pf5InGpM1uMoRkhzFRGnmnL3LPWsQ5a3ag==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}