### Async call the Hello World Orchestration Function
POST http://localhost:7071/api/start/HelloWorld

### Check the status of the Hello World function.
### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@orchestrationInstanceId = 71098a6a1c9c403fb1306ad226fa659c
@storageCode = jLm5dvj2FG6pIVhnZaI2Pf5InGpM1uMoRkhzFRGnmnL3LPWsQ5a3ag==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}


### Synchronous call the Hello World Orchestration Function
POST http://localhost:7071/api/startandwait/HelloWorld
    ?timeout=9
    &interval=3