### ASynchronous call the GetCharacterInfo Orchestration Function
POST http://localhost:7071/api/orchestration/GetCharacterInfo
Content-Type: application/json

"luke"

### Synchronous call the GetCharacterInfo Orchestration Function
POST http://localhost:7071/api/orchestration/GetCharacterInfo/wait
    ?timeout=12
    &interval=3
Content-Type: application/json

"luke"


### Check the status of the orchestration function.
### Update the orchestrationInstanceId and storageCode 
### so it matches the ID of your running orchestration instance.
@orchestrationInstanceId = 0f98445bfe274b739b82791a6a8a983b
@storageCode = jLm5dvj2FG6pIVhnZaI2Pf5InGpM1uMoRkhzFRGnmnL3LPWsQ5a3ag==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}