### Synchronous call the Hello World Orchestration Function
POST http://localhost:7071/api/orchestration/GetCharacterInfo/wait
    ?timeout=12
    &interval=3
Content-Type: application/json

"luke"


### Check the status of the orchestration function.
### Update the orchestrationInstanceId and storageCode 
### so it matches the ID of your running orchestration instance.
@orchestrationInstanceId = b35f52a6388a4870b70380a8091d4b76
@storageCode = yCGdcZ4vAWTSiWHsis5juYX6azfaPUXSbwgk8BnCd473QKi/v9zYsg==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}