### Asynchronous call to the Hello Name Orchestration Function.
POST http://localhost:7071/api/start/HelloName
Content-Type: application/json

"I ❤ Serverless"


### Asynchronous call to the Hello Name Orchestration Function with an instance id.
POST http://localhost:7071/api/start/HelloName/{{$guid}}
Content-Type: application/json

"I ❤ Serverless"


### Checks the status of an orchestration function.
### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@orchestrationInstanceId = d8b1daa9c048474fb89c1139c981f12d
@storageCode = jLm5dvj2FG6pIVhnZaI2Pf5InGpM1uMoRkhzFRGnmnL3LPWsQ5a3ag==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}