### Synchronous call to the Hello Name Orchestration Function.
POST http://localhost:7071/api/startandwait/HelloName
    ?timeout=12
    &interval=2
Content-Type: application/json

"I ❤ Serverless (timeout and interval)"


### Synchronous call to the Hello Name Orchestration Function.
POST http://localhost:7071/api/startandwait/HelloName
    ?timeout=8
Content-Type: application/json

"I ❤ Serverless (only timeout)"


### Synchronous call to the Hello Name Orchestration Function.
POST http://localhost:7071/api/startandwait/HelloName
Content-Type: application/json

"I ❤ Serverless (using defaults)"


### Asynchronous call to the LongRunning Orchestration Function.
### The Execution time will be longer than timeout so the 
### StatusResponseMessage is returned instead of the orchestration result.
POST http://localhost:7071/api/startandwait/LongRunning
    ?timeout=12
    &interval=2
Content-Type: application/json

20

### Checks the status of an orchestration function.
### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@orchestrationInstanceId = d8b1daa9c048474fb89c1139c981f12d
@storageCode = jLm5dvj2FG6pIVhnZaI2Pf5InGpM1uMoRkhzFRGnmnL3LPWsQ5a3ag==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}