### Fan-out/Fan-in Demo
POST http://localhost:7071/api/orchestration/FindClosestMeetups
content-type: application/json

{
    "departureAddress" : "xpirit, hilversum",
    "maxNumberOfEvents" : "3",
    "searchText" : "azure",
    "travelMode" : "driving"
}

### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@instanceid = 2d2f864b5c6e44b58165a072cfd0c9c6
GET http://localhost:7071/admin/extensions/DurableTaskExtension/instances/{{instanceid}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code=3F2oUSLBZALkMA7QxHvaaokuq5Ph/W487ZqydJY1mTaFBni82zlfhQ==