### Function Chaining Demo
POST http://localhost:7071/api/orchestration/MeetupTravelInfo
content-type: application/json

{
    "meetupGroupUrlName" : "Dutch-Azure-Meetup",
    "departureAddress" : "Xpirit, Hilversum",
    "travelMode" : "driving"
}

### Update the orchestrationInstanceId and code variables so they match up with your
### running orchestration instance.
@instanceid = ab3d06c719a1407bb386fd49f70e0bcf
@code = 07hP1FGqaUDMJSQK5S8WaViVCA//XyU5gwgSnGvNc770aaUuFwT9hA== 
GET http://localhost:7071/admin/extensions/DurableTaskExtension/instances/{{instanceid}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{code}}