### Function Chaining Demo
POST http://localhost:7071/api/orchestration/MeetupTravelInfo
content-type: application/json

{
    "meetupGroupUrlName" : "azure-thursdays",
    "departureAddress" : "knab, hoofddorp",
    "travelMode" : "driving"
}

### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@instanceid = 645f09dac19941d39316135af7a6e83c
GET http://localhost:7071/admin/extensions/DurableTaskExtension/instances/{{instanceid}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code=3F2oUSLBZALkMA7QxHvaaokuq5Ph/W487ZqydJY1mTaFBni82zlfhQ==