### Example of using the Google Directions API
# Enter a valid Google Directions API key before you call the endpoints.
@key = %GOOGLE_API_KEY%
@outputFormat = json
@mode = driving
@trafficmodel = pessimistic
@origin = Xpirit, Hilversum
@destination = Ringwade 1, Nieuwegein
@departuretimeepoch = 1517500800000
https://maps.googleapis.com/maps/api/directions/{{outputFormat}}
    ?origin={{origin}}
    &destination={{destination}}
    &mode={{mode}}
    &traffic_model={{trafficmodel}}
    &departure_time={{departuretimeepoch}}
    &key={{key}}

