### Example of using the Meetup API
# Enter a valid Meetup API key before you call the endpoints.
@meetupkey = %MEETUP_API_KEY%

### Get the first event of a given meetup group
@groupname = Azure-Thursdays
GET https://api.meetup.com/{{groupname}}
    ?key={{meetupkey}}
    &sign=true
    &page=2

### Find upcoming events matching the text
GET https://api.meetup.com/find/upcoming_events
    ?key={{meetupkey}}
    &sign=true
    &page=5
    &text=azure

### Find groups based on text search
@text = Azure Thursdays
GET https://api.meetup.com/find/groups
    ?key={{meetupkey}}
    &sign=true
    &text={{text}}
    &page=5

### Retrieve a group based on its group_urlname
@groupname = Azure-Thursdays
GET https://api.meetup.com/2/groups
    ?key={{meetupkey}}
    &sign=true
    &group_urlname={{groupname}}
    &page=1

### Retrieve events of a group based on its group_urlname
@groupname = Azure-Thursdays
GET https://api.meetup.com/2/events
    ?key={{meetupkey}}
    &sign=true
    &group_urlname={{groupname}}
    &page=5

