### Retrieve the status of a specific orchestrator by id.
### Returns a status message.
@instanceId=cfc8fda6fe5241bb9e609f212d28f7be
GET http://localhost:7071/api/status/{{instanceId}}


### Retrieve the status including the history of a specific orchestrator by id.
### Returns a status message.
GET http://localhost:7071/api/status/{{instanceId}}
    ?showHistory=true
    &showHistoryOutput=true


### This is using the default Durable Functions HTTP API to get the status of one instance.
@taskHub = DurableDemo
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{instanceId}}
    ?taskHub={{taskHub}}
    &showHistory=true
    &showHistoryOutput=true
    &showInput=true