### Asynchronous call the GetPlanetResidentsOrchestrator Function
# @name GetPlanetResidents
POST http://localhost:7071/api/start/GetPlanetResidentsOrchestrator
Content-Type: application/json

"tat"

### Synchronous call the GetPlanetResidentsOrchestrator Function
POST http://localhost:7071/api/startandwait/GetPlanetResidentsOrchestrator
    ?timeout=15
    &interval=2
Content-Type: application/json

"tat"


### Check the status of the orchestrator function.
### Update the orchestratorInstanceId and storageCode 
### so it matches the ID of your running orchestrator instance.
@orchestratorInstanceId = {{GetPlanetResidents.response.body.$.id}}
@storageCode = GLoOdgAOebifkr6wfEqmaMSAzrwtRlrSRw7O/gtiarfvo2ofQGmqXQ==
@hubName=DurableDemo
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestratorInstanceId}}
    ?taskHub={{hubName}}
    &connection=Storage
    &code={{storageCode}}