### Asynchronous call the GetPlanetResidents Orchestration Function
POST http://localhost:7071/api/start/GetPlanetResidents
Content-Type: application/json

"tat"

### Synchronous call the GetPlanetResidents Orchestration Function
POST http://localhost:7071/api/startandwait/GetPlanetResidents
    ?timeout=15
    &interval=3
Content-Type: application/json

"tat"


### Check the status of the orchestration function.
### Update the orchestrationInstanceId and storageCode 
### so it matches the ID of your running orchestration instance.
@orchestrationInstanceId = 57c3b27c284d4661915a4c10a82872d5
@storageCode = jLm5dvj2FG6pIVhnZaI2Pf5InGpM1uMoRkhzFRGnmnL3LPWsQ5a3ag==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}