### Synchronous call the Hello World Orchestration Function
POST http://localhost:7071/api/orchestration/GetPlanetResidents/wait
    ?timeout=15
    &interval=3
Content-Type: application/json

"tat"


### Check the status of the orchestration function.
### Update the orchestrationInstanceId and storageCode 
### so it matches the ID of your running orchestration instance.
@orchestrationInstanceId = d4be0b8966324819868ddc82f1069068
@storageCode = yCGdcZ4vAWTSiWHsis5juYX6azfaPUXSbwgk8BnCd473QKi/v9zYsg==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}