### Asynchronous call the GetPlanetResidents Orchestration Function
POST http://localhost:7071/api/orchestration/GetPlanetResidents
Content-Type: application/json

"tat"

### Synchronous call the GetPlanetResidents Orchestration Function
POST http://localhost:7071/api/orchestration/GetPlanetResidents/wait
    ?timeout=15
    &interval=3
Content-Type: application/json

"tat"


### Check the status of the orchestration function.
### Update the orchestrationInstanceId and storageCode 
### so it matches the ID of your running orchestration instance.
@orchestrationInstanceId = a78efde4ec6b468bb904ae7da4326fa5
@storageCode = jLm5dvj2FG6pIVhnZaI2Pf5InGpM1uMoRkhzFRGnmnL3LPWsQ5a3ag==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}