### Call the Hello World Orchestration Function
POST http://localhost:7071/api/orchestration/HelloName/wait
    ?timeout=9
    &interval=3
Content-Type: application/json

"from Durable Functions"

### Check the status of the Hello World function.
### Update this orchestrationInstanceId so it matches the ID of your
### running orchestration instance.
@orchestrationInstanceId = bf404c89f1d7466493f67822a9be7283
@storageCode = yCGdcZ4vAWTSiWHsis5juYX6azfaPUXSbwgk8BnCd473QKi/v9zYsg==
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub=DurableFunctionsHub
    &connection=Storage
    &code={{storageCode}}