### Asynchronous call the GetCharacterInfoOrchestrator Function
# @name GetCharacterInfo
POST http://localhost:7071/api/start/GetCharacterInfoOrchestrator
Content-Type: application/json

"luke"

### Synchronous call the GetCharacterInfoOrchestrator Function
POST http://localhost:7071/api/startandwait/GetCharacterInfoOrchestrator
    ?timeout=15
    &interval=2
Content-Type: application/json

"luke"


### Check the status of the orchestrator function.
### Update the orchestratorInstanceId and storageCode 
### so it matches the ID of your running orchestrator instance.
@orchestratorInstanceId = {{GetCharacterInfo.response.body.$.id}}
@storageCode = GLoOdgAOebifkr6wfEqmaMSAzrwtRlrSRw7O/gtiarfvo2ofQGmqXQ==
@hubName=DurableDemo
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestratorInstanceId}}
    ?taskHub={{hubName}}
    &connection=Storage
    &code={{storageCode}}