### ASynchronous call the GetCharacterInfo Orchestration Function
POST http://localhost:7071/api/start/GetCharacterInfoOrchestration
Content-Type: application/json

"luke"

### Synchronous call the GetCharacterInfo Orchestration Function
POST http://localhost:7071/api/startandwait/GetCharacterInfoOrchestration
    ?timeout=12
    &interval=3
Content-Type: application/json

"luke"


### Check the status of the orchestration function.
### Update the orchestrationInstanceId and storageCode 
### so it matches the ID of your running orchestration instance.
@orchestrationInstanceId = cd56490764114ea79406c3dab1a5bb85
@storageCode = GLoOdgAOebifkr6wfEqmaMSAzrwtRlrSRw7O/gtiarfvo2ofQGmqXQ==
@hubName=DurableDemo
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestrationInstanceId}}
    ?taskHub={{hubName}}
    &connection=Storage
    &code={{storageCode}}