### Delete one instance using the custom httptrigger in the solution.

@instanceId = f5ceb57f4185460dabbf418b4e0116de
DELETE http://localhost:7071/api/purge/{{instanceId}}
Content-Type: application/json

### Delete one instance using the default Durable Functions HTTP API.
@taskHub = DurableDemo
@systemKey = 0
DELETE http://localhost:7071/runtime/webhooks/durabletask/instances/{{instanceId}}
    ?taskHub={{taskHub}}
    &code={{systemKey}}
Content-Type: application/json